### ISSUE TITLE
how is this tool related to az dt model ?

### ISSUE THREAD

**Issue by rido-min** [Azure/opendigitaltwins-tools#15]
What's the recommended option to upload models to ADT?

`az dt model create` seems an overlap with the `UploadModels` tool in this repo.

**Comment by briancr-ms** [comment]
UploadModels is designed to upload an arbitrarily large ontology. For example, "az dt model create" fails trying to upload the opendigitaltwins-building ontology with the following error: The models you are trying to upload exceeds the supported limit. Try breaking up the payload in smaller batches.

Additionally UploadModels will order the upload so that "base" models are uploaded before "leaf" models--this ensures that models uploaded in multiple batches will successfully upload.
