### ISSUE TITLE
issue with using the OWLTODTDL converter

### ISSUE THREAD

**Issue by paraskevizerva** [Azure/opendigitaltwins-tools#157]
Hi there,

I am facing an issue trying to execute the command for the OWLTODTLD converter:

I have tried the example command on my Mac through VisualStudio terminal and Mac terminal : p@@@@@@-MBP opendigitaltwins-tools % ./OWL2DTDL -u https://w3id.org/rec/full/3.3/ -i ./RecIgnoredNames.csv -o /Users/pzerva/Desktop/DTDL/
and I get : zsh: permission denied: ./OWL2DTDL

although I seem to have both r and w access to the files/folders of OWL2DTDL.

Also another question is that in the example execution a URI needs to be provided for the ontology model - what if I have some local ontologies files/models I want to convert in DTDL - is it possible to convert those and what commands I can use?

In addition is there a converter from JSON-LD twins and models to DTDL ?

**Comment by hammar** [comment]
For the other question on JSON-LD and DTDL: JSON-LD is a serialization of RDF. As such, JSON-LD does not enable much more semantics than those provided by RDFs basic graph model (which states that there are things like URI nodes, literal nodes, blank nodes, and they are organized into a directed graph). 

Thus your question becomes (I think?) whether there is a generic converter from RDF graphs to DTDL models. Since one is a data representation and the other is a schema representation, and since there is a semantic mismatch (the primitives of RDF being those listed above, and the primitives of DTDL being things like twins, relationships, properties, components, etc.), I'd say no, such generic translation is not available.

However, data graphs such as twin graphs that are expressed in JSON-LD / RDF are likely adhering to some schematization, expressed in some formal language (either explicitly through the use of a defined shared ontology, or implicitly through adhering to/being generated by some producing/consuming software API). This might be RealEstateCore, or Brick Schema, or SKOS, or W3C SSN, or W3C WoT TD, etc. etc. Some of these are likely to have semantic overlap with DTDL such that translation tooling or workflows could be developed.

I hope I understood the question correctly and that this is of help. Let me know if there's anything else I can do!

Best,

Karl

**Comment by paraskevizerva** [comment]
Thanks for getting back to me that was useful. One more clarification for my second question - I have created my own schematisation yet these ontologies are custom schemas like a domain specific language to describe telemetry metadata so not necessarily adhering to the existing standards and I was trying to make the translation to DTDL. My understanding is that there is no generic translator so even if it is possible to do create a translation from my custom ontology schemas to DTDL this needs to be done manually right?

**Comment by hammar** [comment]
To my knowledge there is no such generic translator for *(anything) to DTDL* mapping, no. Depending on how closely aligned your DSL metamodel is to DTDL, it may be possible to automate some such translation via, e.g. scripting or similar tools, possibly saving a bit of effort.
